version: '3.8'

services:
  zentry-bot:
    build: .
    container_name: zentry-futures-core
    restart: unless-stopped

    environment:
      - TZ=UTC

    volumes:
      - data:/app/data
      - logs:/app/logs

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  logs:
