"""
Zentry Futures Core — Data Transfer Objects.

Defines all dataclasses used throughout the trading system:
RecoveryLayer, Basket, Signal, CoinScore, TradeRecord.

These are lightweight in-memory objects used by the trading engine,
separate from the SQLAlchemy ORM models in core.models.
"""

import time
import uuid
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class RecoveryLayer:
    """The single entry of a position (legacy name retained for DB compatibility).

    SINGLE ENTRY ONLY: every position holds exactly one of these (Layer 1) with
    its entry price, margin, and quantity. There is no Layer 2, no recovery, no
    averaging down. The class/table name is kept so the shared database schema
    (``recovery_layers``) is unchanged.
    """

    layer_number: int
    entry_price: float
    margin: float
    quantity: float
    side: str  # 'long' or 'short'
    timestamp: float = field(default_factory=time.time)
    status: str = 'active'  # 'active' or 'closed'


@dataclass
class Basket:
    """A single-entry position for one symbol/direction (one layer only).

    The basket is the primary unit of position management. It holds exactly one
    layer (single entry — no recovery/averaging), computes aggregate metrics
    (avg entry, total margin), and monitors unrealised PnL for take-profit and
    stop-loss logic. The "basket" name is retained for DB-schema compatibility.
    """

    symbol: str
    side: str  # 'long' or 'short'
    atr_at_entry: float
    volatility: str  # coarse ATR label ('normal'/'high'), kept for the audit row
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    layers: List[RecoveryLayer] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    status: str = 'active'  # 'active' or 'closed'
    leverage: int = 10
    account_id: Optional[int] = None  # None = master account

    # ── Computed Properties ──

    @property
    def avg_entry_price(self) -> float:
        """Quantity-weighted average entry price across active layers."""
        active = self.active_layers
        if not active:
            return 0.0
        total_cost = sum(l.entry_price * l.quantity for l in active)
        total_qty = sum(l.quantity for l in active)
        if total_qty == 0:
            return 0.0
        return total_cost / total_qty

    @property
    def total_margin(self) -> float:
        """Sum of margin deployed across all active layers."""
        return sum(l.margin for l in self.active_layers)

    @property
    def total_quantity(self) -> float:
        """Sum of quantity across all active layers."""
        return sum(l.quantity for l in self.active_layers)

    @property
    def active_layers(self) -> List[RecoveryLayer]:
        """List of layers with status == 'active'."""
        return [l for l in self.layers if l.status == 'active']

    @property
    def layer_count(self) -> int:
        """Number of currently active layers."""
        return len(self.active_layers)

    # ── Methods ──

    def unrealized_pnl(self, current_price: float) -> float:
        """Calculate unrealised PnL at the given market price.

        For long positions: (current_price - avg_entry) * total_quantity
        For short positions: (avg_entry - current_price) * total_quantity

        Args:
            current_price: Current market price.

        Returns:
            Unrealised profit/loss in USDT.
        """
        avg = self.avg_entry_price
        qty = self.total_quantity
        if avg == 0 or qty == 0:
            return 0.0
        if self.side == 'long':
            return (current_price - avg) * qty
        else:
            return (avg - current_price) * qty

    def add_layer(self, layer: RecoveryLayer) -> None:
        """Append a recovery layer to this basket.

        Args:
            layer: The RecoveryLayer to add.
        """
        self.layers.append(layer)

    def close_all(self) -> None:
        """Mark all layers and the basket itself as closed."""
        for layer in self.layers:
            layer.status = 'closed'
        self.status = 'closed'


@dataclass
class Signal:
    """Entry signal generated by the SignalEngine.

    Mean-reversion entry: RSI extreme + Bollinger-band touch, gated by the BTC
    15m trend filter. Field names are preserved for DB compatibility:
      • ``market_regime`` stores the BTC regime string (bullish/bearish/neutral)
      • ``ema200`` stores the Bollinger middle band (SMA period)
      • ``volatility`` stores a coarse ATR label (kept for the audit row)
    """

    symbol: str
    side: str  # 'long' or 'short'
    strength: float  # 0.0 – 1.0 signal quality
    atr: float
    market_regime: str  # BTC regime string (stored in signals.market_regime)
    volatility: str  # coarse label (stored in signals.volatility)
    current_price: float
    ema200: float  # Bollinger middle band (stored in signals.ema200)
    rsi: float
    bb_lower: float = 0.0
    bb_upper: float = 0.0
    reason: str = ''  # human-readable reason for entry
    strength_score: int = 0  # correlation-protection score (0–4)
    timestamp: float = field(default_factory=time.time)


@dataclass
class CoinScore:
    """Composite quality score for a USDT-M futures pair.

    Produced by the CoinScanner and used to rank pairs
    for the dynamic watchlist.
    """

    symbol: str
    volume_24h: float
    atr: float
    atr_score: float  # 0 – 1
    volume_score: float  # 0 – 1
    spread_score: float  # 0 – 1
    funding_rate: float
    funding_score: float  # 0 – 1
    composite_score: float  # weighted combination


@dataclass
class TradeRecord:
    """Immutable record of a completed trade (basket close).

    Stored in the database for performance tracking,
    daily statistics, and backtesting analysis.
    """

    basket_id: str
    symbol: str
    side: str
    entry_price: float
    exit_price: float
    quantity: float
    margin: float
    leverage: int
    pnl: float
    fee: float
    layers_used: int
    entry_time: float
    exit_time: float
    exit_reason: str  # 'tp', 'sl', 'daily_loss_limit', 'protection_lock', 'force_close_all', 'reconciled', 'manual'
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    account_id: Optional[int] = None  # None = master account
